// File generated by Flax Materials Editor
// Version: @0

#define MATERIAL 1
#define MATERIAL_TEXCOORDS 1
#define USE_PER_VIEW_CONSTANTS 1
@3

#include "./Flax/Common.hlsl"
#include "./Flax/MaterialCommon.hlsl"
#include "./Flax/StylizedCloud.hlsl"
#include "./Flax/ShadowsSampling.hlsl"
@7

// Primary constant buffer (with additional material parameters)
META_CB_BEGIN(0, Data)
float4x4 WorldMatrix;
float4x4 ViewProjection;
float3 SunDirection;
float SunIntensity;
float3 SunColor;
float SkyIntensity;
float3 SkyColor;
float Time;
float PerInstanceRandom;
int LocalLightCount;
uint ShadowsBufferAddress;
uint HasShadow;
CloudLocalLight LocalLights[STYLIZED_CLOUD_MAX_LOCAL_LIGHTS];
@1META_CB_END

// Shader resources
@2
// Shadow resources (high registers to avoid material parameter conflicts)
Buffer<float4> CloudShadowsBuffer : register(t14);
Texture2D<float> CloudShadowMap : register(t15);
// Material properties generation input
struct MaterialInput
{
	float3 WorldPosition;
	float TwoSidedSign;
	float2 TexCoord;
#if USE_VERTEX_COLOR
	half4 VertexColor;
#endif
	float3x3 TBN;
	float4 SvPosition;
	float3 PreSkinnedPosition;
	float3 PreSkinnedNormal;
	float3 InstanceOrigin;
	float InstanceParams;
#if USE_CUSTOM_VERTEX_INTERPOLATORS
	float4 CustomVSToPS[CUSTOM_VERTEX_INTERPOLATORS_COUNT];
#endif
};

#define GetInstanceTransform(input) WorldMatrix;

// Removes the scale vector from the local to world transformation matrix
float3x3 RemoveScaleFromLocalToWorld(float3x3 localToWorld)
{
	float scaleX = length(localToWorld[0]);
	float scaleY = length(localToWorld[1]);
	float scaleZ = length(localToWorld[2]);
	float3 invScale = float3(
		scaleX > 0.00001f ? 1.0f / scaleX : 0.0f,
		scaleY > 0.00001f ? 1.0f / scaleY : 0.0f,
		scaleZ > 0.00001f ? 1.0f / scaleZ : 0.0f);
	localToWorld[0] *= invScale.x;
	localToWorld[1] *= invScale.y;
	localToWorld[2] *= invScale.z;
	return localToWorld;
}

float3 TransformTangentVectorToWorld(MaterialInput input, float3 tangentVector)
{
	return mul(tangentVector, input.TBN);
}

float3 TransformWorldVectorToTangent(MaterialInput input, float3 worldVector)
{
	return mul(input.TBN, worldVector);
}

float3 TransformWorldVectorToView(MaterialInput input, float3 worldVector)
{
	return mul(worldVector, (float3x3)ViewMatrix);
}

float3 TransformViewVectorToWorld(MaterialInput input, float3 viewVector)
{
	return mul((float3x3)ViewMatrix, viewVector);
}

float3 TransformLocalVectorToWorld(MaterialInput input, float3 localVector)
{
	float3x3 localToWorld = (float3x3)GetInstanceTransform(input);
	return mul(localVector, localToWorld);
}

float3 TransformWorldVectorToLocal(MaterialInput input, float3 worldVector)
{
	float3x3 localToWorld = (float3x3)GetInstanceTransform(input);
	return mul(localToWorld, worldVector);
}

float3 GetObjectPosition(MaterialInput input)
{
	return input.InstanceOrigin.xyz;
}

float3 GetObjectSize(MaterialInput input)
{
	return float3(1, 1, 1);
}

float GetPerInstanceRandom(MaterialInput input)
{
	return input.InstanceParams;
}

float GetLODDitherFactor(MaterialInput input)
{
	return 0;
}

float4 GetVertexColor(MaterialInput input)
{
#if USE_VERTEX_COLOR
	return input.VertexColor;
#else
	return 1;
#endif
}

@8

// Get material properties function (for vertex shader)
Material GetMaterialVS(MaterialInput input)
{
@5
}

// Get material properties function (for domain shader)
Material GetMaterialDS(MaterialInput input)
{
@6
}

// Get material properties function (for pixel shader)
Material GetMaterialPS(MaterialInput input)
{
@4
}

struct Cloud_VS2PS
{
	float4 Position : SV_Position;
	float3 WorldPos : TEXCOORD0;
	float3 WorldNormal : TEXCOORD1;
	float2 TexCoord : TEXCOORD2;
#if USE_VERTEX_COLOR
	half4 VertexColor : COLOR;
#endif
#if USE_CUSTOM_VERTEX_INTERPOLATORS
	float4 CustomVSToPS[CUSTOM_VERTEX_INTERPOLATORS_COUNT] : TEXCOORD3;
#endif
};

struct CloudPrePassOutput
{
	float4 Color : SV_Target0;
	float Depth : SV_Target1;
	float3 Origin : SV_Target2;
	float4 Normal : SV_Target3;
};

// Pre-pass mesh vertex shader
META_VS(true, FEATURE_LEVEL_ES2)
META_VS_IN_ELEMENT(POSITION, 0, R32G32B32_FLOAT,   0, 0,     PER_VERTEX, 0, true)
META_VS_IN_ELEMENT(TEXCOORD, 0, R16G16_FLOAT,      1, 0,     PER_VERTEX, 0, true)
META_VS_IN_ELEMENT(NORMAL,   0, R10G10B10A2_UNORM, 1, ALIGN, PER_VERTEX, 0, true)
META_VS_IN_ELEMENT(TANGENT,  0, R10G10B10A2_UNORM, 1, ALIGN, PER_VERTEX, 0, true)
META_VS_IN_ELEMENT(TEXCOORD, 1, R16G16_FLOAT,      1, ALIGN, PER_VERTEX, 0, true)
Cloud_VS2PS VS_CloudPrePass(ModelInput input)
{
	Cloud_VS2PS output;

	// Build material input for VS
	MaterialInput materialInput = (MaterialInput)0;
	materialInput.WorldPosition = input.Position.xyz;
	materialInput.TexCoord = input.TexCoord0;
	materialInput.PreSkinnedPosition = input.Position.xyz;
	materialInput.PreSkinnedNormal = input.Normal.xyz * 2.0 - 1.0;
	materialInput.TBN = float3x3(float3(1,0,0), float3(0,1,0), materialInput.PreSkinnedNormal);
	materialInput.InstanceOrigin = WorldMatrix[3].xyz;
	materialInput.InstanceParams = PerInstanceRandom;
	materialInput.TwoSidedSign = 1.0f;
#if USE_VERTEX_COLOR
	materialInput.VertexColor = input.Color;
#endif

	Material material = GetMaterialVS(materialInput);

	float3 localPos = input.Position.xyz + material.PositionOffset;
	float4 worldPos = mul(float4(localPos, 1), WorldMatrix);
	output.Position = mul(worldPos, ViewProjection);
	output.WorldPos = worldPos.xyz;
	float3 normal = normalize(input.Normal.xyz * 2.0 - 1.0);
	output.WorldNormal = normalize(mul(normal, (float3x3)WorldMatrix));
	output.TexCoord = input.TexCoord0;
#if USE_VERTEX_COLOR
	output.VertexColor = input.Color;
#endif
#if USE_CUSTOM_VERTEX_INTERPOLATORS
	output.CustomVSToPS = materialInput.CustomVSToPS;
#endif

	return output;
}

// Pre-pass mesh pixel shader
META_PS(true, FEATURE_LEVEL_ES2)
CloudPrePassOutput PS_CloudPrePass(Cloud_VS2PS input)
{
	CloudPrePassOutput output;

	// Build material input for PS
	MaterialInput materialInput = (MaterialInput)0;
	materialInput.WorldPosition = input.WorldPos;
	materialInput.TexCoord = input.TexCoord;
	materialInput.TBN = float3x3(float3(1, 0, 0), float3(0, 1, 0), normalize(input.WorldNormal));
	materialInput.TwoSidedSign = 1.0f;
	materialInput.SvPosition = input.Position;
	materialInput.InstanceOrigin = WorldMatrix[3].xyz;
	materialInput.InstanceParams = PerInstanceRandom;
#if USE_VERTEX_COLOR
	materialInput.VertexColor = input.VertexColor;
#endif
#if USE_CUSTOM_VERTEX_INTERPOLATORS
	materialInput.CustomVSToPS = input.CustomVSToPS;
#endif

	Material material = GetMaterialPS(materialInput);

	// Cloud lighting
	float3 n = normalize(input.WorldNormal);

	// Sample directional light shadow
	float sunShadow = 1.0f;
	if (HasShadow)
	{
		LightData dirLight = (LightData)0;
		// ShaderLightData.Direction points toward the light (negated emission dir)
		dirLight.Direction = -SunDirection;
		dirLight.ShadowsBufferAddress = ShadowsBufferAddress;
		// Build a GBufferSample with Normal facing the sun so the NoL early-out
		// doesn't trigger (clouds are translucent and always need shadow lookup).
		GBufferSample gBuf = (GBufferSample)0;
		gBuf.ShadingModel = SHADING_MODEL_LIT;
		gBuf.WorldPos = input.WorldPos;
		gBuf.Normal = -SunDirection;
		gBuf.ViewPos.z = length(input.WorldPos - ViewPos);
		ShadowSample shadow = SampleDirectionalLightShadow(dirLight, CloudShadowsBuffer, CloudShadowMap, gBuf);
		sunShadow = shadow.SurfaceShadow;
	}

	float3 lightColor = ComputeStylizedCloudLighting(
		input.WorldPos, n, ViewPos,
		SunDirection, SunIntensity, SunColor,
		SkyIntensity, SkyColor,
		sunShadow,
		LocalLightCount, LocalLights);

	// Combine material outputs with lighting
	float3 finalColor = material.Color * lightColor + material.Emissive;

	// Mask is a hard cutout; Opacity is soft density
	clip(material.Mask - 0.5f);
	output.Color = float4(finalColor, max(material.Opacity, 0.0f));
	output.Origin = WorldMatrix[3].xyz;
	output.Normal = float4(n, 0);
	// Linearize device depth using per-view constants: ViewInfo.w / (depth - ViewInfo.z)
	float linearDepth = ViewInfo.w / (input.Position.z - ViewInfo.z);
	output.Depth = linearDepth * max(ViewFar, 1.0f);
	return output;
}

@9
