// File generated by Flax Materials Editor
// Version: @0

#define MATERIAL 1
#define MATERIAL_TEXCOORDS 1
#define USE_PER_VIEW_CONSTANTS 1
@3

#include "./Flax/Common.hlsl"
#include "./Flax/MaterialCommon.hlsl"
#include "./Flax/StylizedCloud.hlsl"
#include "./Flax/ShadowsSampling.hlsl"
#include "./Flax/Matrix.hlsl"
@7

// Primary constant buffer (with additional material parameters)
META_CB_BEGIN(0, Data)
// Particle data
float4x3 WorldMatrix;
uint SortedIndicesOffset;
float PerInstanceRandom;
int ParticleStride;
int PositionOffset;
int VelocityOffset;
int RotationOffset;
int ScaleOffset;
int ModelFacingModeOffset;
// Ribbon data (aligned to 16-byte register boundaries)
float2 RibbonUVScale;
float2 RibbonUVOffset;
float RibbonUVTilingDistance;
int RibbonWidthOffset;
int RibbonTwistOffset;
int RibbonFacingVectorOffset;
uint RibbonSegmentCount;
float RibbonPadding0;
float RibbonPadding1;
float RibbonPadding2;
float4x3 WorldMatrixInverseTransposed;
// Cloud lighting data
float4x4 ViewProjection;
float3 SunDirection;
float SunIntensity;
float3 SunColor;
float SkyIntensity;
float3 SkyColor;
float Time;
int LocalLightCount;
uint ShadowsBufferAddress;
uint HasShadow;
float CloudParticlePadding0;
CloudLocalLight LocalLights[STYLIZED_CLOUD_MAX_LOCAL_LIGHTS];
@1META_CB_END

// Particles attributes buffer
ByteAddressBuffer ParticlesData : register(t0);

// Sorted particles indices
Buffer<uint> SortedIndices : register(t1);

// Shader resources
@2
// Shadow resources (high registers to avoid material parameter conflicts)
Buffer<float4> CloudShadowsBuffer : register(t14);
Texture2D<float> CloudShadowMap : register(t15);

// Material properties generation input
struct MaterialInput
{
	float3 WorldPosition;
	float TwoSidedSign;
	float2 TexCoord;
	uint ParticleIndex;
#if USE_VERTEX_COLOR
	half4 VertexColor;
#endif
	float3x3 TBN;
	float4 SvPosition;
	float3 PreSkinnedPosition;
	float3 PreSkinnedNormal;
	float3 InstanceOrigin;
	float InstanceParams;
#if USE_CUSTOM_VERTEX_INTERPOLATORS
	float4 CustomVSToPS[CUSTOM_VERTEX_INTERPOLATORS_COUNT];
#endif
};

#define GetInstanceTransform(input) ToMatrix4x4(WorldMatrix);

// Removes the scale vector from the local to world transformation matrix
float3x3 RemoveScaleFromLocalToWorld(float3x3 localToWorld)
{
	float scaleX = length(localToWorld[0]);
	float scaleY = length(localToWorld[1]);
	float scaleZ = length(localToWorld[2]);
	float3 invScale = float3(
		scaleX > 0.00001f ? 1.0f / scaleX : 0.0f,
		scaleY > 0.00001f ? 1.0f / scaleY : 0.0f,
		scaleZ > 0.00001f ? 1.0f / scaleZ : 0.0f);
	localToWorld[0] *= invScale.x;
	localToWorld[1] *= invScale.y;
	localToWorld[2] *= invScale.z;
	return localToWorld;
}

float3 TransformTangentVectorToWorld(MaterialInput input, float3 tangentVector)
{
	return mul(tangentVector, input.TBN);
}

float3 TransformWorldVectorToTangent(MaterialInput input, float3 worldVector)
{
	return mul(input.TBN, worldVector);
}

float3 TransformWorldVectorToView(MaterialInput input, float3 worldVector)
{
	return mul(worldVector, (float3x3)ViewMatrix);
}

float3 TransformViewVectorToWorld(MaterialInput input, float3 viewVector)
{
	return mul((float3x3)ViewMatrix, viewVector);
}

float3 TransformLocalVectorToWorld(MaterialInput input, float3 localVector)
{
	float3x3 localToWorld = (float3x3)GetInstanceTransform(input);
	return mul(localVector, localToWorld);
}

float3 TransformWorldVectorToLocal(MaterialInput input, float3 worldVector)
{
	float3x3 localToWorld = (float3x3)GetInstanceTransform(input);
	return mul(localToWorld, worldVector);
}

float3 GetObjectPosition(MaterialInput input)
{
	return input.InstanceOrigin.xyz;
}

float3 GetObjectSize(MaterialInput input)
{
	return float3(1, 1, 1);
}

float GetPerInstanceRandom(MaterialInput input)
{
	return input.InstanceParams;
}

float GetLODDitherFactor(MaterialInput input)
{
	return 0;
}

float4 GetVertexColor(MaterialInput input)
{
#if USE_VERTEX_COLOR
	return input.VertexColor;
#else
	return 1;
#endif
}

uint GetParticleUint(uint particleIndex, int offset)
{
	return ParticlesData.Load(particleIndex * ParticleStride + offset);
}

int GetParticleInt(uint particleIndex, int offset)
{
	return asint(ParticlesData.Load(particleIndex * ParticleStride + offset));
}

float GetParticleFloat(uint particleIndex, int offset)
{
	return asfloat(ParticlesData.Load(particleIndex * ParticleStride + offset));
}

float2 GetParticleVec2(uint particleIndex, int offset)
{
	return asfloat(ParticlesData.Load2(particleIndex * ParticleStride + offset));
}

float3 GetParticleVec3(uint particleIndex, int offset)
{
	return asfloat(ParticlesData.Load3(particleIndex * ParticleStride + offset));
}

float4 GetParticleVec4(uint particleIndex, int offset)
{
	return asfloat(ParticlesData.Load4(particleIndex * ParticleStride + offset));
}

float3 TransformParticlePosition(float3 input)
{
	return mul(float4(input, 1.0f), ToMatrix4x4(WorldMatrix)).xyz;
}

float3 TransformParticleVector(float3 input)
{
	return mul(float4(input, 0.0f), ToMatrix4x4(WorldMatrixInverseTransposed)).xyz;
}

@8

// Get material properties function (for vertex shader)
Material GetMaterialVS(MaterialInput input)
{
@5
}

// Get material properties function (for domain shader)
Material GetMaterialDS(MaterialInput input)
{
@6
}

// Get material properties function (for pixel shader)
Material GetMaterialPS(MaterialInput input)
{
@4
}

// Calculates the transform matrix from mesh tangent space to local space
half3x3 CalcTangentToLocal(ModelInput input)
{
	float bitangentSign = input.Tangent.w ? -1.0f : +1.0f;
	float3 normal = input.Normal.xyz * 2.0 - 1.0;
	float3 tangent = input.Tangent.xyz * 2.0 - 1.0;
	float3 bitangent = cross(normal, tangent) * bitangentSign;
	return (half3x3)float3x3(tangent, bitangent, normal);
}

half3x3 CalcTangentToWorld(in float4x4 world, in half3x3 tangentToLocal)
{
	half3x3 localToWorld = (half3x3)RemoveScaleFromLocalToWorld((float3x3)world);
	return mul(tangentToLocal, localToWorld);
}

float3 GetParticlePosition(uint particleIndex)
{
	return TransformParticlePosition(GetParticleVec3(particleIndex, PositionOffset));
}

struct Cloud_VS2PS
{
	float4 Position : SV_Position;
	float3 WorldPos : TEXCOORD0;
	float3 WorldNormal : TEXCOORD1;
	float2 TexCoord : TEXCOORD2;
	uint ParticleIndex : TEXCOORD3;
#if USE_VERTEX_COLOR
	half4 VertexColor : COLOR;
#endif
#if USE_CUSTOM_VERTEX_INTERPOLATORS
	float4 CustomVSToPS[CUSTOM_VERTEX_INTERPOLATORS_COUNT] : TEXCOORD4;
#endif
};

struct RibbonInput
{
	uint Order : TEXCOORD0;
	uint ParticleIndex : TEXCOORD1;
	uint PrevParticleIndex : TEXCOORD2;
	float Distance : TEXCOORD3;
};

struct CloudPrePassOutput
{
	float4 Color : SV_Target0;
	float Depth : SV_Target1;
	float3 Origin : SV_Target2;
	float4 Normal : SV_Target3;
};

// Vertex Shader function for Model Rendering (particle instanced)
META_VS(true, FEATURE_LEVEL_ES2)
META_VS_IN_ELEMENT(POSITION, 0, R32G32B32_FLOAT,   0, 0,     PER_VERTEX, 0, true)
META_VS_IN_ELEMENT(TEXCOORD, 0, R16G16_FLOAT,      1, 0,     PER_VERTEX, 0, true)
META_VS_IN_ELEMENT(NORMAL,   0, R10G10B10A2_UNORM, 1, ALIGN, PER_VERTEX, 0, true)
META_VS_IN_ELEMENT(TANGENT,  0, R10G10B10A2_UNORM, 1, ALIGN, PER_VERTEX, 0, true)
META_VS_IN_ELEMENT(TEXCOORD, 1, R16G16_FLOAT,      1, ALIGN, PER_VERTEX, 0, true)
META_VS_IN_ELEMENT(COLOR,    0, R8G8B8A8_UNORM,    2, 0,     PER_VERTEX, 0, USE_VERTEX_COLOR)
Cloud_VS2PS VS_Model(ModelInput input, uint particleIndex : SV_InstanceID)
{
	Cloud_VS2PS output;

	// Sorted particles mapping
	if (SortedIndicesOffset != 0xFFFFFFFF)
	{
		particleIndex = SortedIndices[SortedIndicesOffset + particleIndex];
	}

	// Read particle data
	float4x4 worldMatrix = ToMatrix4x4(WorldMatrix);
	float3 particlePosition = GetParticleVec3(particleIndex, PositionOffset);
	float3 particleScale = GetParticleVec3(particleIndex, ScaleOffset);
	float3 particleRotation = GetParticleVec3(particleIndex, RotationOffset);
	int modelFacingMode = ModelFacingModeOffset != -1 ? GetParticleInt(particleIndex, ModelFacingModeOffset) : -1;
	float3 position = mul(float4(particlePosition, 1), worldMatrix).xyz;

	// Compute final vertex position in the world
	float3x3 eulerMatrix = EulerMatrix(radians(particleRotation));
	float4 transform0 = float4(eulerMatrix[0], particlePosition.x);
	float4 transform1 = float4(eulerMatrix[1], particlePosition.y);
	float4 transform2 = float4(eulerMatrix[2], particlePosition.z);
	float4x4 scaleMatrix = float4x4(float4(particleScale.x, 0.0f, 0.0f, 0.0f), float4(0.0f, particleScale.y, 0.0f, 0.0f), float4(0.0f, 0.0f, particleScale.z, 0.0f), float4(0.0f, 0.0f, 0.0f, 1.0f));
	float4x4 world = float4x4(transform0, transform1, transform2, float4(0.0f, 0.0f, 0.0f, 1.0f));
	if (modelFacingMode == 0)
	{
		// Face Camera Position
		float3 direction = normalize(ViewPos - position);
		float4 alignmentQuat = FindQuatBetween(float3(1.0f, 0.0f, 0.0f), direction);
		float4x4 alignmentMat = QuaternionToMatrix(alignmentQuat);
		world = mul(world, mul(alignmentMat, scaleMatrix));
	}
	else if (modelFacingMode == 1)
	{
		// Face Camera Plane
		float3 direction = -ViewDir;
		float4 alignmentQuat = FindQuatBetween(float3(1.0f, 0.0f, 0.0f), direction);
		float4x4 alignmentMat = QuaternionToMatrix(alignmentQuat);
		world = mul(world, mul(alignmentMat, scaleMatrix));
	}
	else if (modelFacingMode == 2)
	{
		// Along Velocity
		float3 direction = GetParticleVec3(particleIndex, VelocityOffset);
		float4 alignmentQuat = FindQuatBetween(float3(1.0f, 0.0f, 0.0f), normalize(direction));
		float4x4 alignmentMat = QuaternionToMatrix(alignmentQuat);
		world = mul(world, mul(alignmentMat, scaleMatrix));
	}
	else
	{
		// Default
		world = mul(world, scaleMatrix);
	}
	world = transpose(world);
	world = mul(world, worldMatrix);

	// Calculate the vertex position in world space
	float3 worldPos = mul(float4(input.Position, 1), world).xyz;
	output.WorldPos = worldPos;

	// Compute clip space position
	output.Position = mul(float4(worldPos, 1), ViewProjection);

	// Calculate world normal
	half3x3 tangentToLocal = CalcTangentToLocal(input);
	half3x3 tangentToWorld = CalcTangentToWorld(worldMatrix, tangentToLocal);
	output.WorldNormal = normalize(tangentToWorld[2]);

	// Pass vertex attributes
	output.TexCoord = input.TexCoord0;
	output.ParticleIndex = particleIndex;
#if USE_VERTEX_COLOR
	output.VertexColor = input.Color;
#endif

	// Build material input for VS
	MaterialInput materialInput = (MaterialInput)0;
	materialInput.WorldPosition = worldPos;
	materialInput.TexCoord = input.TexCoord0;
	materialInput.ParticleIndex = particleIndex;
	materialInput.PreSkinnedPosition = input.Position.xyz;
	materialInput.PreSkinnedNormal = tangentToLocal[2].xyz;
	materialInput.TBN = (float3x3)tangentToWorld;
	materialInput.InstanceOrigin = worldMatrix[3].xyz;
	materialInput.InstanceParams = PerInstanceRandom;
	materialInput.TwoSidedSign = 1.0f;
#if USE_VERTEX_COLOR
	materialInput.VertexColor = input.Color;
#endif

	Material material = GetMaterialVS(materialInput);

	// Apply world position offset per-vertex
#if USE_POSITION_OFFSET
	output.WorldPos += material.PositionOffset;
	output.Position = mul(float4(output.WorldPos, 1), ViewProjection);
#endif

#if USE_CUSTOM_VERTEX_INTERPOLATORS
	output.CustomVSToPS = materialInput.CustomVSToPS;
#endif

	return output;
}

// Vertex Shader function for Ribbon Rendering
META_VS(true, FEATURE_LEVEL_ES2)
META_VS_IN_ELEMENT(TEXCOORD, 0, R32_UINT,   0, 0,     PER_VERTEX, 0, true)
META_VS_IN_ELEMENT(TEXCOORD, 1, R32_UINT,   0, ALIGN, PER_VERTEX, 0, true)
META_VS_IN_ELEMENT(TEXCOORD, 2, R32_UINT,   0, ALIGN, PER_VERTEX, 0, true)
META_VS_IN_ELEMENT(TEXCOORD, 3, R32_FLOAT,  0, ALIGN, PER_VERTEX, 0, true)
Cloud_VS2PS VS_Ribbon(RibbonInput input, uint vertexIndex : SV_VertexID)
{
	Cloud_VS2PS output;

	// Get particle data
	uint particleIndex = input.ParticleIndex;
	int vertexSign = (((int)vertexIndex & 0x1) * 2) - 1;
	float3 position = GetParticlePosition(particleIndex);
	float ribbonWidth = RibbonWidthOffset != -1 ? GetParticleFloat(particleIndex, RibbonWidthOffset) : 20.0f;
	float ribbonTwist = RibbonTwistOffset != -1 ? GetParticleFloat(particleIndex, RibbonTwistOffset) : 0.0f;

	// Calculate ribbon direction
	float3 direction;
	if (input.Order == 0)
	{
		direction = GetParticlePosition(input.PrevParticleIndex) - position;
	}
	else
	{
		direction = position - GetParticlePosition(input.PrevParticleIndex);
	}

	// Calculate particle orientation (tangent vectors)
	float3 cameraDirection = SafeNormalize(ViewPos - position);
	float3 tangentUp = SafeNormalize(direction);
	float3 facing = RibbonFacingVectorOffset != -1 ? GetParticleVec3(particleIndex, RibbonFacingVectorOffset) : cameraDirection;
	float twistSine, twistCosine;
	sincos(radians(ribbonTwist), twistSine, twistCosine);
	facing = facing * twistCosine + cross(facing, tangentUp) * twistSine + tangentUp * dot(tangentUp, facing) * (1 - twistCosine);
	float3 tangentRight = SafeNormalize(cross(tangentUp, facing));
	if (!any(tangentRight))
	{
		tangentRight = SafeNormalize(cross(tangentUp, float3(0.0f, 0.0f, 1.0f)));
	}

	// Calculate texture coordinates
	float2 texCoord;
	if (RibbonUVTilingDistance != 0.0f)
	{
		texCoord.x = input.Distance / RibbonUVTilingDistance;
	}
	else
	{
		texCoord.x = (float)input.Order / (float)RibbonSegmentCount;
	}
	texCoord.y = (float)((vertexIndex + 1) & 0x1);
	texCoord = texCoord * RibbonUVScale + RibbonUVOffset;
	output.TexCoord = texCoord;

	// Compute world space vertex position
	float3 worldPos = position + tangentRight * vertexSign * (ribbonWidth.xxx * 0.5f);
	output.WorldPos = worldPos;

	// Compute clip space position using cloud-specific ViewProjection
	output.Position = mul(float4(worldPos, 1), ViewProjection);

	// Calculate world normal from ribbon tangent frame
	output.WorldNormal = normalize(cross(tangentRight, tangentUp));

	// Pass vertex attributes
	output.ParticleIndex = particleIndex;
#if USE_VERTEX_COLOR
	output.VertexColor = 1;
#endif

	// Build material input for VS
	MaterialInput materialInput = (MaterialInput)0;
	materialInput.WorldPosition = worldPos;
	materialInput.TexCoord = texCoord;
	materialInput.ParticleIndex = particleIndex;
#if USE_VERTEX_COLOR
	materialInput.VertexColor = 1;
#endif
	half3x3 tangentToLocal = half3x3(tangentRight, tangentUp, cross(tangentRight, tangentUp));
	float4x4 world = ToMatrix4x4(WorldMatrix);
	half3x3 tangentToWorld = CalcTangentToWorld(world, tangentToLocal);
	materialInput.TBN = (float3x3)tangentToWorld;
	materialInput.TwoSidedSign = 1.0f;
	materialInput.SvPosition = output.Position;
	materialInput.PreSkinnedPosition = position;
	materialInput.PreSkinnedNormal = tangentToLocal[2].xyz;
	materialInput.InstanceOrigin = world[3].xyz;
	materialInput.InstanceParams = PerInstanceRandom;

	Material material = GetMaterialVS(materialInput);

	// Apply world position offset per-vertex
#if USE_POSITION_OFFSET
	output.WorldPos += material.PositionOffset;
	output.Position = mul(float4(output.WorldPos, 1), ViewProjection);
#endif

#if USE_CUSTOM_VERTEX_INTERPOLATORS
	output.CustomVSToPS = materialInput.CustomVSToPS;
#endif

	return output;
}

// Pre-pass cloud pixel shader (particle instanced)
META_PS(true, FEATURE_LEVEL_ES2)
CloudPrePassOutput PS_CloudPrePass(Cloud_VS2PS input)
{
	CloudPrePassOutput output;

	// Build material input for PS
	MaterialInput materialInput = (MaterialInput)0;
	materialInput.WorldPosition = input.WorldPos;
	materialInput.TexCoord = input.TexCoord;
	materialInput.ParticleIndex = input.ParticleIndex;
	materialInput.TBN = float3x3(float3(1, 0, 0), float3(0, 1, 0), normalize(input.WorldNormal));
	materialInput.TwoSidedSign = 1.0f;
	materialInput.SvPosition = input.Position;
	materialInput.InstanceOrigin = ToMatrix4x4(WorldMatrix)[3].xyz;
	materialInput.InstanceParams = PerInstanceRandom;
#if USE_VERTEX_COLOR
	materialInput.VertexColor = input.VertexColor;
#endif
#if USE_CUSTOM_VERTEX_INTERPOLATORS
	materialInput.CustomVSToPS = input.CustomVSToPS;
#endif

	Material material = GetMaterialPS(materialInput);

	// Cloud lighting
	float3 n = normalize(input.WorldNormal);

	// Sample directional light shadow
	float sunShadow = 1.0f;
	if (HasShadow)
	{
		LightData dirLight = (LightData)0;
		dirLight.Direction = -SunDirection;
		dirLight.ShadowsBufferAddress = ShadowsBufferAddress;
		// Normal faces sun so the NoL early-out doesn't trigger (clouds are translucent)
		GBufferSample gBuf = (GBufferSample)0;
		gBuf.ShadingModel = SHADING_MODEL_LIT;
		gBuf.WorldPos = input.WorldPos;
		gBuf.Normal = -SunDirection;
		gBuf.ViewPos.z = length(input.WorldPos - ViewPos);
		ShadowSample shadow = SampleDirectionalLightShadow(dirLight, CloudShadowsBuffer, CloudShadowMap, gBuf);
		sunShadow = shadow.SurfaceShadow;
	}

	float3 lightColor = ComputeStylizedCloudLighting(
		input.WorldPos, n, ViewPos,
		SunDirection, SunIntensity, SunColor,
		SkyIntensity, SkyColor,
		sunShadow,
		LocalLightCount, LocalLights);

	// Combine material outputs with lighting
	float3 finalColor = material.Color * lightColor + material.Emissive;

	// Mask is a hard cutout; Opacity is soft density
	clip(material.Mask - 0.5f);
	output.Color = float4(finalColor, max(material.Opacity, 0.0f));
	output.Origin = ToMatrix4x4(WorldMatrix)[3].xyz;
	output.Normal = float4(n, 0);
	// Linearize device depth using per-view constants
	float linearDepth = ViewInfo.w / (input.Position.z - ViewInfo.z);
	output.Depth = linearDepth * max(ViewFar, 1.0f);
	return output;
}

@9
